Repository precice/python-bindings, pull requests merged in 2020-11, with the labels that each got.

#66 add Spack to documentation
  CHANGELOG.md
  README.md
  docs/ReleaseGuide.md
Labels: documentation

#69 Handle writing of empty arrays to preCICE
  CHANGELOG.md
  precice.pyx
  test/test_bindings_module.pyx
Labels: bug

#70 Use python-versioneer to support __version__
  .gitattributes
  .gitignore
  MANIFEST.in
  cyprecice/.gitignore
  cyprecice/SolverInterface.pxd
  cyprecice/cyprecice.pxd
  cyprecice/cyprecice.pyx
  docs/ReleaseGuide.md
  precice/.gitignore
  precice/__init__.py
  precice/_version.py
  setup.cfg
  setup.py
  versioneer.py
Labels: bug, enhancement

#73 Fix bug: It looks like opal_init failed for some reason
  cyprecice/cyprecice.pxd
  cyprecice/cyprecice.pyx
Labels: bug

#68 Test spack build with CI and provide instructions and tools for release
  .github/workflows/build-spack.yml
  docs/ReleaseGuide.md
  spack/README.md
  spack/ci-spack-pyprecice-deps-1804.dockerfile
  spack/jinja-instantiate.py
  spack/var/spack/repos/builtin/packages/py-pyprecice/deactivate-version-check-via-pip.patch
  spack/var/spack/repos/builtin/packages/py-pyprecice/package.py
Labels: enhancement
