Repository precice/python-bindings, pull requests merged in 2020-01, with the labels that each got.

#13 Moving configure call into interface initialization
  precice.pyx
Labels: enhancement

#17 Add CI
  .travis.yml
  README.md
Labels: enhancement

#28 Adding Migration Guide
  docs/MigrationGuide.md
Labels: documentation

#30 Compatibility: markActionFulfilled and isTimeWindowComplete
  SolverInterface.pxd
  precice.pyx
  solverdummy/precice-config.xml
  solverdummy/solverdummy.py
  test/SolverInterface.cpp
Labels: compatibility
