Repository precice/python-bindings, pull requests merged in 2020-02, with the labels that each got.

#32 Fix the requirements of the solverdummy
  solverdummy/requirements.txt
Labels: bug

#33 docstring documentation for python-bindings
  precice.pyx
Labels: documentation

#36 Remove MPI from python bindings
  setup.py
  solverdummy/README.md
  solverdummy/solverdummy_parallel.py
Labels: enhancement

#35 Publish package on PyPI
  .github/workflows/pythonpublish.yml
  README.md
  solverdummy/README.md
  solverdummy/solverdummy.py
  solverdummy/solverdummy_parallel.py
Labels: enhancement

#43 Provide PyPI-friendly package description
  setup.py
Labels: documentation
