Repository precice/python-bindings, pull requests merged in 2021-04, with the labels that each got.

#96 Release v2.2.0.2
  .github/workflows/build-env.yml
  .github/workflows/build-spack.yml
  CHANGELOG.md
  README.md
  cyprecice/cyprecice.pyx
  docs/ReleaseGuide.md
  precice/__init__.py
  solverdummy/requirements.txt
  spack/README.md
  spack/ci-spack-pyprecice-deps-1804.dockerfile
  spack/jinja-instantiate.py
  spack/repo/packages/py-pyprecice/deactivate-version-check-via-pip.patch
  spack/repo/packages/py-pyprecice/package.py
  spack/repo/repo.yaml
Labels: enhancement

#98 Check PEP8: Exit 1 on failure and line length 120
  .github/workflows/check-pep8.yml
Labels: bug

#100 Test solverdummy
  .github/workflows/run-solverdummy.yml
Labels: enhancement

#103 Remove Travis CI
  .github/workflows/build-and-test.yml
  .travis.yml
  README.md
Labels: compatibility
