Repository precice/python-bindings, pull requests merged in 2024-07, with the labels that each got.

#204 Fix numpy include order
  setup.py
Labels: bug

#206 Fix and update spack testing, update `package.py`, rectify checksum of `v2.5.0.1`
  .github/workflows/build-env.yml
  .github/workflows/build-spack.yml
  spack/README.md
  spack/ci-spack-pyprecice-deps-2404.dockerfile
  spack/repo/packages/py-pyprecice/package.py
Labels: compatibility

#207 Require setuptools>=61
  CHANGELOG.md
  pyproject.toml
  setup.py
  spack/repo/packages/py-pyprecice/package.py
Labels: maintainability
