Repository precice/python-bindings, pull requests merged in 2025-03, with the labels that each got.

#225 Add exception support
  cyprecice/Participant.pxd
Labels: enhancement

#230 Update installation instructions
  README.md
Labels: documentation

#231 Add API functions for Just-in-time mapping
  cyprecice/Participant.pxd
  cyprecice/cyprecice.pyx
  test/Participant.cpp
  test/test_bindings_module.py
Labels: compatibility

#233 Update requirements of the solver dummy
  changelog-entries/233.md
  examples/solverdummy/requirements.txt
Labels: compatibility
